// Code generated by mockery v2.42.0. DO NOT EDIT.

package controller

import (
	context "context"
	model "kvart-info/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// mockUsecase is an autogenerated mock type for the usecase type
type mockUsecase struct {
	mock.Mock
}

type mockUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *mockUsecase) EXPECT() *mockUsecase_Expecter {
	return &mockUsecase_Expecter{mock: &_m.Mock}
}

// GetSummaryInfo provides a mock function with given fields: ctx
func (_m *mockUsecase) GetSummaryInfo(ctx context.Context) ([]model.SummaryInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSummaryInfo")
	}

	var r0 []model.SummaryInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.SummaryInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.SummaryInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SummaryInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockUsecase_GetSummaryInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSummaryInfo'
type mockUsecase_GetSummaryInfo_Call struct {
	*mock.Call
}

// GetSummaryInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockUsecase_Expecter) GetSummaryInfo(ctx interface{}) *mockUsecase_GetSummaryInfo_Call {
	return &mockUsecase_GetSummaryInfo_Call{Call: _e.mock.On("GetSummaryInfo", ctx)}
}

func (_c *mockUsecase_GetSummaryInfo_Call) Run(run func(ctx context.Context)) *mockUsecase_GetSummaryInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockUsecase_GetSummaryInfo_Call) Return(_a0 []model.SummaryInfo, _a1 error) *mockUsecase_GetSummaryInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockUsecase_GetSummaryInfo_Call) RunAndReturn(run func(context.Context) ([]model.SummaryInfo, error)) *mockUsecase_GetSummaryInfo_Call {
	_c.Call.Return(run)
	return _c
}

// newMockUsecase creates a new instance of mockUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockUsecase {
	mock := &mockUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
