// Code generated by mockery v2.42.0. DO NOT EDIT.

package service

import (
	context "context"
	model "kvart-info/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// mockRepository is an autogenerated mock type for the repository type
type mockRepository struct {
	mock.Mock
}

type mockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRepository) EXPECT() *mockRepository_Expecter {
	return &mockRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx
func (_m *mockRepository) Get(ctx context.Context) ([]model.SummaryInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []model.SummaryInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.SummaryInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.SummaryInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SummaryInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockRepository_Expecter) Get(ctx interface{}) *mockRepository_Get_Call {
	return &mockRepository_Get_Call{Call: _e.mock.On("Get", ctx)}
}

func (_c *mockRepository_Get_Call) Run(run func(ctx context.Context)) *mockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockRepository_Get_Call) Return(_a0 []model.SummaryInfo, _a1 error) *mockRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRepository_Get_Call) RunAndReturn(run func(context.Context) ([]model.SummaryInfo, error)) *mockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// newMockRepository creates a new instance of mockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRepository {
	mock := &mockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
